### ISSUE TITLE
Some keys in eval_dic are missing in the preprocessed data

### ISSUE THREAD

**Issue by ruslanmustafin** [Nicholasli1995/VisualizingNDF#2] opened 2019-11-26 13:55 UTC
Hi,

Thanks for your amazing work. I was trying to run your code and got FileNotFound for some items present in the evaluation dict. I downloaded all the data to the folder as per the documentation.

To reproduce, run the following snippet from `src/age_estimation`:

```
import glob
import numpy as np

eval_dic = np.load('../data/CACD_split/test_cacd_processed.npy', allow_pickle=True).item()
available_imgs = glob.glob('../data/CACD2000_processed/*.jpg')

for key in eval_dic.keys():
    for p in eval_dic[key]['path']:
        if not p in available_imgs:
            print(key)
            break
```

This should print
```
Mädchen Amick 
Alexander Skarsgård 
Penélope Cruz 
Daniel Brühl 
Stellan Skarsgård 
```

**Comment by Nicholasli1995** [comment] 2019-11-29 03:57
Hi I'm updating the training and testing code. This will be fixed soon.

**Comment by Nicholasli1995** [comment] 2019-11-30 14:00
Hi, it seems the images are contained in my local CACD2000_processed folder. I have updated the training code. Can you check it again to see whether the problem is still there? If so I can re-upload the images if some of them are missing.

> Hi,
> 
> Thanks for your amazing work. I was trying to run your code and got FileNotFound for some items present in the evaluation dict. I downloaded all the data to the folder as per the documentation.
> 
> To reproduce, run the following snippet from `src/age_estimation`:
> 
> ```
> import glob
> import numpy as np
> 
> eval_dic = np.load('../data/CACD_split/test_cacd_processed.npy', allow_pickle=True).item()
> available_imgs = glob.glob('../data/CACD2000_processed/*.jpg')
> 
> for key in eval_dic.keys():
>     for p in eval_dic[key]['path']:
>         if not p in available_imgs:
>             print(key)
>             break
> ```
> 
> This should print
> 
> ```
> Mädchen Amick 
> Alexander Skarsgård 
> Penélope Cruz 
> Daniel Brühl 
> Stellan Skarsgård 
> ```

**Comment by Nicholasli1995** [comment] 2019-12-15 12:01
Closed due to no reply. Re-open it if needed.

**Closed as completed by Nicholasli1995** 2019-12-15 12:01 UTC
